name: transbeamer_lib_ci
on:
  pull_request:
    paths:
      - 'lib/**'
  workflow_dispatch:
    inputs:
      wait_for_ssh:
        type: boolean
        description: 'If true, wait for an SSH connection when finished'
        required: false
        default: false

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run clean build
        run: |
          ./gradlew clean :lib:build
          ./gradlew convertNDJsonToCSV

      - name: Debugging SSH Session
        env:
          NPM_TOKEN: ${{ secrets.CIVIAN_GITHUB_PACKAGES_READ_TOKEN }}
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.wait_for_ssh }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
