name: transbeamer_lib_cd
on:
  push:
    paths:
      - 'lib/gradle.properties'
    branches:
      - main
  workflow_dispatch:
    inputs:
      wait_for_ssh:
        type: boolean
        description: 'If true, wait for an SSH connection when finished'
        required: false
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish package
        run: |
          ./gradlew :lib:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debugging SSH Session
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.wait_for_ssh }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
